version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    container_name: astroflow-status
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    # If your container needs outbound internet on university networks:
    # network_mode: host
